#!/usr/bin/env python3
"""Join each gap factory's building_chain with satisfactory.db to produce
per-recipe item-level inputs/outputs -> gap-factory-details.json.

This is the AUTHORITATIVE numbers source for the per-factory detail tabs in
factory-map.html. building_chain (recipe, building, rates, building counts) is
copied verbatim from gap-factory-locations.json (the optimizer's output); only
the per-recipe ingredient/product item rates are looked up here and scaled by
buildings_exact so the chain stays internally balanced.

Run after find_gap_factory_locations.py. Reproducible / stdlib-only.
"""
import json
import sqlite3

DB = '/Users/deepak/AI/satisfy/satisfactory.db'
SRC = '/Users/deepak/AI/satisfy/gap-factory-locations.json'
OUT = '/Users/deepak/AI/satisfy/gap-factory-details.json'

# resource key (optimizer) -> ore item name (game)
RES_TO_ORE = {
    'iron': 'Iron Ore', 'copper': 'Copper Ore', 'bauxite': 'Bauxite',
    'coal': 'Coal', 'quartz': 'Raw Quartz', 'limestone': 'Limestone',
    'caterium': 'Caterium Ore', 'oil': 'Crude Oil', 'sulfur': 'Sulfur',
    'nitrogen': 'Nitrogen Gas', 'sam': 'SAM',
}


def fluid(item_name, qty):
    """DB stores fluids as mL (x1000). Convert to m^3 for display."""
    FLUIDS = {'Water', 'Crude Oil', 'Heavy Oil Residue', 'Fuel', 'Turbofuel',
              'Liquid Biofuel', 'Alumina Solution', 'Sulfuric Acid',
              'Nitric Acid', 'Nitrogen Gas', 'Dissolved Silica', 'Rocket Fuel',
              'Ionized Fuel', 'Quantum Energy', 'Dark Matter Residue',
              'Excited Photonic Matter'}
    return qty / 1000.0 if item_name in FLUIDS else qty


def recipe_io(db, recipe_name, want_item, want_building):
    """Return (duration, [(item, per_min_in)], [(item, per_min_out)]) for the
    recipe row matching name (+ disambiguated by product item / building)."""
    rows = db.execute("SELECT id, duration FROM recipes WHERE name = ?",
                      (recipe_name,)).fetchall()
    if not rows:
        raise SystemExit(f"recipe not found: {recipe_name!r}")
    if len(rows) > 1:
        # disambiguate: prefer the recipe that outputs want_item AND is built
        # in want_building
        best = None
        for rid, dur in rows:
            prods = [r['name'] for r in db.execute(
                "SELECT i.name FROM recipe_products rp JOIN items i ON i.id=rp.item_id "
                "WHERE rp.recipe_id=?", (rid,))]
            blds = [r['name'] for r in db.execute(
                "SELECT b.name FROM recipe_buildings rb JOIN buildings b ON b.id=rb.building_id "
                "WHERE rb.recipe_id=?", (rid,))]
            if want_item in prods and (not want_building or want_building in blds):
                best = (rid, dur)
                break
        rows = [best] if best else rows[:1]
    rid, dur = rows[0]
    ins = [(r['name'], fluid(r['name'], r['quantity']) / dur * 60)
           for r in db.execute(
               "SELECT i.name, ri.quantity FROM recipe_ingredients ri "
               "JOIN items i ON i.id=ri.item_id WHERE ri.recipe_id=?", (rid,))]
    outs = [(r['name'], fluid(r['name'], r['quantity']) / dur * 60)
            for r in db.execute(
                "SELECT i.name, rp.quantity FROM recipe_products rp "
                "JOIN items i ON i.id=rp.item_id WHERE rp.recipe_id=?", (rid,))]
    return dur, ins, outs


def main():
    db = sqlite3.connect(DB)
    db.row_factory = sqlite3.Row
    src = json.load(open(SRC))
    fl = src['factory_locations']
    out = {'meta': {'description': 'Per-factory recipe/building/input/output '
                    'detail. Numbers joined from gap-factory-locations.json '
                    'building_chain x satisfactory.db. Generated by '
                    'compute_factory_details.py.',
                    'source': 'gap-factory-locations.json + satisfactory.db'},
           'factories': {}}

    for fid, f in fl.items():
        recipes = []
        consumed = {}   # item -> total per-min consumed across all steps
        produced = {}   # item -> total per-min produced across all steps
        for c in f['building_chain']:
            m = c['buildings_exact']  # scale factor: per-building rate -> step rate
            dur, ins, outs = recipe_io(db, c['recipe'], c['item'], c['building'])
            step_in = [{'item': it, 'per_min': round(r * m, 1)} for it, r in ins]
            step_out = [{'item': it, 'per_min': round(r * m, 1)} for it, r in outs]
            for it, r in ins:
                consumed[it] = consumed.get(it, 0) + r * m
            for it, r in outs:
                produced[it] = produced.get(it, 0) + r * m
            recipes.append({
                'recipe': c['recipe'],
                'building': c['building'],
                'buildings': c['buildings_ceil'],
                'buildings_exact': round(c['buildings_exact'], 2),
                'power_mw': round(c['power_mw'], 1),
                'primary_item': c['item'],
                'primary_per_min': round(c['rate_per_min'], 1),
                'consumes': step_in,
                'produces': step_out,
            })

        # net per item: produced - consumed. Positive & not a raw ore = factory
        # output surplus; ~0 = internal intermediate; negative = imported/raw.
        net = {}
        for it in set(consumed) | set(produced):
            net[it] = round(produced.get(it, 0) - consumed.get(it, 0), 1)

        # Ores from the optimizer's authoritative per-resource demand.
        raw_inputs = [{'item': RES_TO_ORE.get(k, k), 'per_min': round(v['demand'], 1)}
                      for k, v in f.get('resources', {}).items()]
        ore_set = {x['item'] for x in raw_inputs}
        targets = f.get('targets', {})
        outputs = [{'item': k, 'per_min': v} for k, v in targets.items()]

        # External inputs beyond ores: net-negative items that aren't ores =
        # Water (extractors, free) + imported intermediates (e.g. Petroleum Coke).
        FREE_FLUID = {'Water'}
        declared_imports = f.get('imports_resolved', [])
        external_inputs = []
        for it, n in sorted(net.items()):
            if it in ore_set or n >= -0.5:
                continue
            is_free = it in FREE_FLUID
            is_import = it in declared_imports
            # skip sub-2/min undeclared deficits: per-step ceil/rounding noise.
            if not is_free and not is_import and n > -2.0:
                continue
            external_inputs.append({
                'item': it, 'per_min': round(-n, 1),
                'source': 'water extractor (free)' if is_free
                else ('import' if is_import else 'upstream deficit')})
        # Byproducts: net-positive items that aren't declared targets (>1/min).
        byproducts = [{'item': it, 'per_min': n} for it, n in sorted(net.items())
                      if n > 1.0 and it not in targets]

        out['factories'][fid] = {
            'id': fid,
            'factory_name': f.get('factory_name', fid),
            'theme': f.get('theme', ''),
            'kind': f.get('kind', ''),
            'disposition': f.get('disposition', ''),
            'signature_resource': f.get('signature_resource', ''),
            'center': f.get('center'),
            'total_shards': f.get('total_shards', 0),
            'totals': f.get('building_totals', {}),
            'imports': f.get('imports_resolved', []),
            'outputs': outputs,
            'raw_inputs': raw_inputs,
            'external_inputs': external_inputs,
            'byproducts': byproducts,
            'sites': f.get('sites', []),
            'outposts': f.get('outposts', []),
            'recipes': recipes,
            'net_per_item': net,
        }

    json.dump(out, open(OUT, 'w'), indent=2)
    print(f"wrote {OUT}: {len(out['factories'])} factories")
    # quick console sanity: list any net negative non-raw items (would be an
    # unsupplied intermediate = chain imbalance)
    ore_names = set(RES_TO_ORE.values())
    FREE = {'Water'}
    for fid, fd in out['factories'].items():
        # genuine imbalance = an intermediate under-produced by >2/min that is
        # neither an ore, free fluid, nor a declared import. (<2/min = per-step
        # ceil/rounding noise on multi-hundred/min bases.)
        bad = {it: n for it, n in fd['net_per_item'].items()
               if n < -2.0 and it not in ore_names and it not in FREE
               and it not in fd['imports']}
        if bad:
            print(f"  [check] {fid}: net-negative intermediates {bad}")
    print("  (no [check] lines above = all chains balance within rounding)")


if __name__ == '__main__':
    main()
